blog/urls.py
# -*- coding: utf-8 -*-#

# -------------------------------------------------------------------------------
# Name:         urls
# Description:  
# Author:       buer1990
# Date:         2018/12/20
# -------------------------------------------------------------------------------

from django.conf.urls import url
from . import views

"""
        比如说我们本地开发服务器的域名是 http://127.0.0.1:8000，
        那么当用户输入网址 http://127.0.0.1:8000 后，Django 
        首先会把协议 http、域名 127.0.0.1 和端口号 8000 去掉，
        此时只剩下一个空字符串，而 r'^$' 的模式正是匹配一个空字符串
        （这个正则表达式的意思是以空字符串开头且以空字符串结尾），
        于是二者匹配，Django 便会调用其对应的 views.index 函数
"""
# 通过 app_name='blog' 告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesViews.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^search/$', views.search, name='search'),
]

comments/urls.py
# -*- coding: utf-8 -*-#

# -------------------------------------------------------------------------------
# Name:         urls
# Description:  
# Author:       buer1990
# Date:         2019/1/9
# -------------------------------------------------------------------------------
from django.conf.urls import url

from comments import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'blog/', include('blog.urls')),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls'))
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.six import python_2_unicode_compatible

# Create your models here.
import markdown


class Category(models.Model):
    """
        文章分类

        Django 要求模型必须继承 models.Model 类。
        Category 只需要一个简单的分类名 name 就可以了。
        CharField 指定了分类名 name 的数据类型，CharField 是字符型，
        CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
        当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
        Django 内置的全部类型可查看文档：
        https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)


class Tag(models.Model):
    """
        文章标签
    """
    name = models.CharField(max_length=100)


@python_2_unicode_compatible
class Post(models.Model):
    """
        文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=100, blank=True)
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category, on_delete=models.CASCADE, )  # CASCADE：此值设置，是级联删除。
    """
        在django2.0后，定义外键和一对一关系的时候需要加on_delete选项，此参数为了避免两个表里的数据不一致问题，不然会报错：
        TypeError: __init__() missing 1 required positional argument: 'on_delete'
        举例说明：
        user=models.OneToOneField(User)
        owner=models.ForeignKey(UserProfile)
        需要改成：
        user=models.OneToOneField(User,on_delete=models.CASCADE) --在老版本这个参数（models.CASCADE）是默认值
        owner=models.ForeignKey(UserProfile,on_delete=models.CASCADE) --在老版本这个参数（models.CASCADE）是默认值
        参数说明：
        on_delete有CASCADE、PROTECT、SET_NULL、SET_DEFAULT、SET()五个可选择的值
        CASCADE：此值设置，是级联删除。
        PROTECT：此值设置，是会报完整性错误。
        SET_NULL：此值设置，会把外键设置为null，前提是允许为null。
        SET_DEFAULT：此值设置，会把设置为外键的默认值。
        SET()：此值设置，会调用外面的值，可以是一个函数。
        一般情况下使用CASCADE就可以了。
    """
    tags = models.ManyToManyField(Tag, blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User, on_delete=models.CASCADE, )

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        # 因为之前将reverse写成了reversed 方法，导致页面在获取当前连接时候出错，谨慎呐
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 文章按最新发表排序
    class Meta:
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:100]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models

from django.utils.six import python_2_unicode_compatible


# python manage.py makemigrations
# python manage.py migrate

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=225)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:3]

blog/views.py
import markdown
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

from blog.models import Post, Category
from comments.forms import CommentForm

"""

"""
# def index(request):
#     # return HttpResponse("欢迎访问我的博客网站！")
#     # return render(request, "blog/index.html", context={
#     #                  'title': '我的博客首页',
#     #                  'welcome': '欢迎访问我的博客首页',
#     #              })
#     post_list = Post.objects.all()
#     # print(post)
#     return render(request, 'blog/index.html', context={'post_list': post_list, })
"""

"""


# IndexView
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 4


# def detail(request, pk):
#     post0 = get_object_or_404(Post, pk=pk)
#     post0.increase_views()
#     post0.body = markdown.markdown(post0.body, extensions={'markdown.extensions.extra',
#                                                            'markdown.extensions.codehilite',
#                                                            'markdown.extensions.toc',
#                                                            })
#
#     # 记得在顶部导入 CommentForm
#     form = CommentForm()
#     # 获取这篇 post 下的全部评论
#     comment_list = post0.comment_set.all()
#     # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据
#     context = {'post0': post0,
#                'form': form,
#                'comment_list': comment_list}
#     return render(request, 'blog/detail.html', context=context)
"""

"""


# PostDetailView
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post0'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲
        post0 = super(PostDetailView, self).get_object(queryset=None)
        post0.body = markdown.markdown(post0.body, extensions={'markdown.extensions.extra',
                                                               'markdown.extensions.codehilite',
                                                               'markdown.extensions.toc',
                                                               })
        return post0

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context


"""

"""


# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month,
#                                     ).order_by('created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})

#  ArchivesViews
class ArchivesViews(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('nonth')
        return super(ArchivesViews, self).get_queryset().filter(created_time__year=year,
                                                                created_time__month=month,
                                                                )


"""

"""

# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})

"""

"""


# CategoryView
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


def listing(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 3)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/index.html', {'posts': posts})


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键字'
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    # 双下划线，带出某modle 下属性的方法,其中方法前的'i'表示不区分大小写
    # 并且可以看到，有外联关系表结构会出现外联属性，like:author__post__body__contains
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    <article class="post post-{{ post0.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">{{ post0.title }}</h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post0.category.name }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post0.created_time }}">{{ post0.created_time }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post0.author }}</a></span>
                                <span class="comments-link"><a href="{{ post0.get_absolute_url }}">{{ post0.comment_set.count }} 评论</a></span>
                                <span class="views-count"><a href="{{ post0.get_absolute_url }}">{{ post0.views }} 阅读</a></span>
                            </div>

                        </header>
                        <div class="entry-content clearfix">
    {{ post0.body|safe }}

{# safe 是 Django 模板系统中的过滤器（Filter），可以简单地把它看成是一种函数，#}
{#其作用是作用于模板变量，将模板变量的值变为经过滤器处理过后的值。例如这里 {{ post.body|safe }}，#}
{#本来 {{ post.body }} 经模板系统渲染后应该显示 body 本身的值，但是在后面加上 safe 过滤器后，#}
{#渲染的值不再是body 本身的值，而是由 safe 函数处理后返回的值。#}
{#过滤器的用法是在模板变量后加一个 | 管道符号，再加上过滤器的名称。#}
{#可以连续使用多个过滤器，例如 {{ var|filter1|filter2 }}   #}

 </div>
                    </article>
                    <section class="comment-area" id="comment-area">
                        <hr>
                        <h3>发表评论</h3>
                        <form action="{% url 'comments:post_comment' post0.pk %}" method="post" class="comment-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="{{  form.name.id_for_label }}">名字：</label>
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                </div>
                                <div class="col-md-4">
                                    <label for="{{  form.email.id_for_label }}">邮箱：</label>
                                    {{ form.email }}
                                    {{ form.email.errors }}
                                </div>
                                <div class="col-md-4">
                                    <label for="{{ form.url.id_for_label }}">URL：</label>
                                    {{ form.url }}
                                    {{ form.url.errors }}
                                </div>
                                <div class="col-md-12">
                                    <label for="{{ form.text.id_for_label }}">评论：</label>
                                    {{ form.text }}
                                    {{ form.text.errors }}
                                    <button type="submit" class="comment-btn">发表</button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                        <div class="comment-list-panel">
                            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
                            <ul class="comment-list list-unstyled">
                                {% for comment in comment_list %}
                                    <li class="comment-item">
                                        <span class="nickname">{{ comment.name }}</span>
                                        <time class="submit-date" >{{ comment.created_time }}</time>
                                        <div class="text">
                                {{ comment.text }}
                                </div>
                                    </li>
                                {% empty %}
                                    暂时还没有人评论！
                                {% endfor %}
                            </ul>
                        </div>
                    </section>
                </main>

            </div>
        </div>
    </div>
{% endblock main %}

templates/blog/index.html
{#继承 base.html#}
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
            <div class="entry-content clearfix">
                {#{{ post.body | truncatechars:201 }}#}
                <p>{{ post.excerpt }}......</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>

        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果  -->
    {% if is_paginated %}
        <div class="pagination-simple">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            <!-- 显示当前页面信息 -->
            <span class="current">第 {{ page_obj.number }}页 / 共 {{ page_obj.paginator.num_pages  }}  页</span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% endif %}
    <div class="pagination">
    </div>
{% endblock main %}