blog/urls.py
# -*- coding: utf-8 -*-#

# -------------------------------------------------------------------------------
# Name:         urls
# Description:  
# Author:       buer1990
# Date:         2018/12/20
# -------------------------------------------------------------------------------

from django.conf.urls import url
from . import views

"""
        比如说我们本地开发服务器的域名是 http://127.0.0.1:8000，
        那么当用户输入网址 http://127.0.0.1:8000 后，Django 
        首先会把协议 http、域名 127.0.0.1 和端口号 8000 去掉，
        此时只剩下一个空字符串，而 r'^$' 的模式正是匹配一个空字符串
        （这个正则表达式的意思是以空字符串开头且以空字符串结尾），
        于是二者匹配，Django 便会调用其对应的 views.index 函数
"""
# 通过 app_name='blog' 告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesViews.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^search/$', views.search, name='search'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'blog/', include('blog.urls')),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls'))
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.six import python_2_unicode_compatible

# Create your models here.
import markdown


class Category(models.Model):
    """
        文章分类

        Django 要求模型必须继承 models.Model 类。
        Category 只需要一个简单的分类名 name 就可以了。
        CharField 指定了分类名 name 的数据类型，CharField 是字符型，
        CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
        当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
        Django 内置的全部类型可查看文档：
        https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)


class Tag(models.Model):
    """
        文章标签
    """
    name = models.CharField(max_length=100)


@python_2_unicode_compatible
class Post(models.Model):
    """
        文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=100, blank=True)
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category, on_delete=models.CASCADE, )  # CASCADE：此值设置，是级联删除。
    """
        在django2.0后，定义外键和一对一关系的时候需要加on_delete选项，此参数为了避免两个表里的数据不一致问题，不然会报错：
        TypeError: __init__() missing 1 required positional argument: 'on_delete'
        举例说明：
        user=models.OneToOneField(User)
        owner=models.ForeignKey(UserProfile)
        需要改成：
        user=models.OneToOneField(User,on_delete=models.CASCADE) --在老版本这个参数（models.CASCADE）是默认值
        owner=models.ForeignKey(UserProfile,on_delete=models.CASCADE) --在老版本这个参数（models.CASCADE）是默认值
        参数说明：
        on_delete有CASCADE、PROTECT、SET_NULL、SET_DEFAULT、SET()五个可选择的值
        CASCADE：此值设置，是级联删除。
        PROTECT：此值设置，是会报完整性错误。
        SET_NULL：此值设置，会把外键设置为null，前提是允许为null。
        SET_DEFAULT：此值设置，会把设置为外键的默认值。
        SET()：此值设置，会调用外面的值，可以是一个函数。
        一般情况下使用CASCADE就可以了。
    """
    tags = models.ManyToManyField(Tag, blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User, on_delete=models.CASCADE, )

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        # 因为之前将reverse写成了reversed 方法，导致页面在获取当前连接时候出错，谨慎呐
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 文章按最新发表排序
    class Meta:
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:100]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">


    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>
<body>
<!-- 其它内容 -->
<script src="{% static 'blog/js/script.js' %}"></script>
{#创建一个基础页面模板，main标签 中可变的个性化内容。#}
<main class="col-md-8">
    {% block main %}

    {% endblock main %}

</main>

<aside class="col-md-4">
    {% block toc %}
        <aside class="col-md-4">
            <div class="widget widget-content">
                <h3 class="widget-title">文章目录</h3>
                <ul>
                    <li>
                        <a href="#">教程特点</a>
                    </li>
                    <li>
                        <a href="#">谁适合这个教程</a>
                    </li>
                    <li>
                        <a href="#">在线预览</a>
                    </li>
                    <li>
                        <a href="#">资源列表</a>
                    </li>
                    <li>
                        <a href="#">获取帮助</a>
                    </li>
                </ul>
            </div>
            <div class="widget widget-recent-posts">
                <h3 class="widget-title">最新文章</h3>
                {% get_recent_posts as recent_post_list %}
                <ul>
                    {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    {% empty %}
                        暂无文章！
                    {% endfor %}
                </ul>
            </div>
            <div class="widget widget-archives">
                <h3 class="widget-title">归档</h3>
                {% archives as date_list  %}
                <ul>
                    {% for date in date_list  %}
                        <li>
                            <a href="{% url 'blog:archives'  date.year date.month %}">
                                {{ date.year }}年{{ date.month }}月</a>
                        </li>
                        </ul>
                    {% empty %}
                        暂无归档！
                    {% endfor %}
            </div>

            <div class="widget widget-category">
                <h3 class="widget-title">分类</h3>
                {% get_categories as category_list %}
                <ul>
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">
                                ({{ category.post_set.count }})</span></a>
                        </li>
                    {% empty %}
                        暂无分类！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget widget-tag-cloud">
                <h3 class="widget-title">标签云</h3>
                <ul>
                    <li>
                        <a href="#">Django</a>
                    </li>
                    <li>
                        <a href="#">Python</a>
                    </li>
                    <li>
                        <a href="#">Java</a>
                    </li>
                    <li>
                        <a href="#">笔记</a>
                    </li>
                    <li>
                        <a href="#">文档</a>
                    </li>
                    <li>
                        <a href="#">AngularJS</a>
                    </li>
                    <li>
                        <a href="#">CSS</a>
                    </li>
                    <li>
                        <a href="#">JavaScript</a>
                    </li>
                    <li>
                        <a href="#">Snippet</a>
                    </li>
                    <li>
                        <a href="#">jQuery</a>
                    </li>
                </ul>
            </div>
            <div class="rss">
                <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
            </div>
        </aside>
    {% endblock toc %}
</aside>
<footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2017 - Collect from <a href="http://test.crm.hipac.cn/index.html"
                                                                      target="_blank" title="hipac">洋驼家测试</a>
                        - Modified by <a href="https://github.com/buer1990/Myblog" title="我的博客" target="_blank">测试工程师</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>